#第六章 用户模型

如果在运行`bundle exec annotate --position before`时得到

	Unable to annotate user.rb: `attr_accessible` is extracted out of Rails into a gem. 
	Please use new recommended protection model for params(strong_parameters) or add `protected_attributes` to your Gemfile to use old one.
	Nothing annotated.

我试着将`app/models/user.rb`中的``attr_accessible``换为`protected_attributes`

但是在后面打开rails控制台的时候却出现了错误

所以我改为在`gemfile`中加入`gem 'protected_attributes'`,这下就没问题了.


需要注意，如果使用 attr_accessible 定义了某些属性是可访问的，那么就只有这些可访问的属性才能使用 update_attributes 方法更新。如果模型突然拒绝更新某些属性的话，你就可以检查一下这些属性是否在 attr_accessible 方法中。

运行`bundle exec rspec spec/`
报第一个错

	You don't have bcrypt-ruby installed in your application. Please add it to your Gemfile and run bundle install
	/usr/local/lib/ruby/gems/2.0.0/gems/bundler-1.5.3/lib/bundler/rubygems_integration.rb:250:in `block in replace_gem': can't activate bcrypt-ruby (~> 3.1.2), already activated bcrypt-ruby-3.0.1. Make sure all dependencies are added to Gemfile. (Gem::LoadError)

解决方法是将`gemfile`中的`gem 'bcrypt-ruby', '3.0.1'`替换为`gem 'bcrypt-ruby', '~> 3.1.2'`即可

第二个错

	........[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
	F.........FFF................

	Failures:

	  1) User 
	     Failure/Error: it { should be_valid }
	       expected valid? to return true, got false
	     # ./spec/models/user_spec.rb:31:in `block (2 levels) in <top (required)>'

	  2) User with valid password 
	     Failure/Error: it { should == found_user.authenticate(@user.password) }
	     NameError:
	       undefined local variable or method `found_user' for #<RSpec::Core::ExampleGroup::Nested_2::Nested_11:0x235f0a50>
	     # ./spec/models/user_spec.rb:100:in `block (3 levels) in <top (required)>'

	  3) User with invalid password 
	     Failure/Error: let(:user_for_invalid_password) { found_user.authenticate("invalid") }
	     NameError:
	       undefined local variable or method `found_user' for #<RSpec::Core::ExampleGroup::Nested_2::Nested_12:0x235fb8ec>
	     # ./spec/models/user_spec.rb:104:in `block (3 levels) in <top (required)>'
	     # ./spec/models/user_spec.rb:106:in `block (3 levels) in <top (required)>'

	  4) User with invalid password 
	     Failure/Error: let(:user_for_invalid_password) { found_user.authenticate("invalid") }
	     NameError:
	       undefined local variable or method `found_user' for #<RSpec::Core::ExampleGroup::Nested_2::Nested_12:0x235fa910>
	     # ./spec/models/user_spec.rb:104:in `block (3 levels) in <top (required)>'
	     # ./spec/models/user_spec.rb:107:in `block (3 levels) in <top (required)>'

	Finished in 2.57 seconds
	37 examples, 4 failures

	Failed examples:

	rspec ./spec/models/user_spec.rb:31 # User 
	rspec ./spec/models/user_spec.rb:100 # User with valid password 
	rspec ./spec/models/user_spec.rb:106 # User with invalid password 
	rspec ./spec/models/user_spec.rb:107 # User with invalid password 

找解决方法时,我发现我没在`subject { @user }`中加入`it { should respond_to(:authenticate) }`
不过加入之后,错误还是没有被解决

Google了好久,还是没有找到方法,只得请高手帮忙了,[cod7ce](https://github.com/cod7ce)给出了以下的帮助:

错误

	1) User
	   Failure/Error: it { should be_valid }
	   expected valid? to return true, got false

这个问题是由于执行rspec时，数据库记录没有清空造成的,因为我user模型测试时，有save操作,数据库中已经存在了，所以valid时，email重复了.可以试试[这个](https://github.com/bmabey/database_cleaner),这是配置教程:[英文配置教程](http://devblog.avdi.org/2012/08/31/configuring-database_cleaner-with-rails-rspec-capybara-and-selenium/)和[中文配置教程](http://jianshu.io/p/9f7823cae6ef)

错误:

	  2) User with valid password 
	     Failure/Error: it { should == found_user.authenticate(@user.password) }

是由于 `@user.save()` 后，将信息写入数据库
再使用 `let(:found_user) { User.find_by_email(@user.email) }`
获取的found_user是存在id和时间戳的,而测试的上下文中的用户实体是你第23行代码所指的
使用new方法构造的，并没有id 和时间戳，所以对象内容不一致导致的.

我表示用了`database_cleaner`之后,爽爆了!

  * [目录](README.md)
  * [第五章 完善布局](04.md)
  * [第七章 用户注册](06.md)